### PR TITLE
Dependencies update; version bump

### PR DESCRIPTION
**Pull request by danielparks**
The new icinga2api package is slightly different.

### CODE REVIEW

**Comment by danielparks** [comment]
Hm. I was hoping this would include Charles's changes too. :(

**Comment by danielparks** [comment]
Oops, I see what happened.

**Comment by danielparks** [comment]
Eh. I'll just leave it like this.

**Comment by danielparks** [comment]
It now sets downtime on services automatically.

**Comment by danielparks** [comment]
And includes @charlesdunbar's changes, since I packaged it with them.

**Review by mattkirby — APPROVED** [review]

**Pull request merged**
